myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  extension_to_extension_velocity_controller:
    type: velocity_controllers/JointPositionController
    joint: extention_to_extension
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Velocity Controllers ---------------------------------------
  right_front_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_base_to_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_front_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_base_to_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_base_to_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: back_base_to_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  
